version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./backend/src/main/resources/private_key.pem:/app/src/main/resources/private_key.pem:ro

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend